apiVersion: cnat.testcrd.dev/v1
kind: At
metadata:
  labels:
    app.kubernetes.io/name: at
    app.kubernetes.io/instance: at-sample
    app.kubernetes.io/part-of: atcontroller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: atcontroller
  name: at-sample
spec:
  # TODO(user): Add fields here
